version: "3.8"
services:
    dev_db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
        volumes:
            - /var/lib/postgresql/data
        ports:
            - "5432:5432"
        container_name: postgres_dev_db
